name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install gtest
      run: sudo apt-get install libgtest-dev
    - name: sudo apt-get install cmake
      run: sudo apt-get install cmake
    - name: cd /usr/src/gtest
      run: cd /usr/src/gtest 
    - name: sudo cmake /usr/src/gtest/CMakeLists.txt
      run: sudo cmake /usr/src/gtest/CMakeLists.txt 
    - name: sudo make
      run: sudo make
    - name: configure
      run: mkdir build && cd debug_release
    - name: make
      run: cd debug_release && make 
    - name: make
      run:  make
    - name: test
      run: ./build_debug/my_printf
