name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest
      run: sudo apt-get install libgtest-dev 
    - name: cd /usr/src/gtest
      run: cd /usr/src/gtest 
    - name: sudo cmake /usr/src/gtest/CMakeLists.txt
      run: sudo cmake /usr/src/gtest/CMakeLists.txt 
    - name:  sudo make
      run: sudo make 
    - name: sudo cp *.a /usr/lib
      run: sudo cp *.a /usr/lib 
    - name: sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libtest.a
      run: sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libtest.a 
    - name: sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
      run: sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: test
      run: ./build_debug/my_printf
