name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

      
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: sudo apt install nasm
      run: sudo apt install nasm
    - name: Install gtest
      run: sudo apt-get install libgtest-dev
    - name: cd /usr/src/gtest
      run: cd /usr/src/gtest
    - name: cd to my directory
      run: cd /home/runner/work/printf/printf
    - name: display current dir
      run: pwd
    - name: create folders
      run: make init
    - name: make release
      run: make --file=/home/runner/work/printf/printf/Makefile
    - name: run
      run: ./release/my_printf
