name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install nasm
      run: sudo apt install nasm
    - name: install gtest
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest
    - name: cd to my directory
      run: cd /home/runner/work/printf/printf
    - name: create folders
      run: make init
    - name: make debug
      run: make --file=/home/runner/work/printf/printf/Makefile
    - name: run
      run: ./debug/my_printf

      
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: sudo apt install nasm
      run: sudo apt install nasm
    - name: install gtest
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest
    - name: cd to my directory
      run: cd /home/runner/work/printf/printf
    - name: create folders
      run: make init
    - name: make release
      run: make release
    - name: run
      run: ./release/my_printf
