name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
          fetch-depth: 1
    - name: make
      run:  make
    - name: test
      run: ./build_debug/my_printf
